[pytest]
markers =
    generate_logprob: /generate logprob tests; require interface generate_logprob
    generate_experts: /generate routed-experts tests; require interface generate_experts
python_files = test*_*.py  # test file
python_classes = Test*     # test class
python_functions = test_*  # test function
pytest_runtest_call.tryfirst = True
filterwarnings = ignore::UserWarning
reruns = 2
reruns_delay = 1
