# HF model id: internlm/internlm2_5-7b-chat

a100:
- model_type: chat
  engine_config:
    tp: 1
    extra:
      tool-call-parser: internlm2
  backends:
  - name: turbomind
    communicators:
    - nccl
  - name: pytorch
    communicators:
    - nccl
  test_coverage:
  - interface
  interface:
  - tool_parser
h:
- model_type: chat
  engine_config:
    tp: 1
    extra:
      tool-call-parser: internlm2
  backends:
  - name: turbomind
    communicators:
    - nccl
  - name: pytorch
    communicators:
    - nccl
  test_coverage:
  - interface
  interface:
  - tool_parser
