# HF model id: Qwen/Qwen3-8B-FP8

a100:
- model_type: chat
  engine_config:
    tp: 1
    extra:
      reasoning-parser: qwen-qwq
      tool-call-parser: qwen3
  backends:
  - name: turbomind
    communicators:
    - nccl
  - name: pytorch
    communicators:
    - nccl
  test_coverage:
  - interface
  interface:
  - reasoning_parser
  - tool_parser
  gen_config:
    chat-template-kwargs:
      enable_thinking: true
h:
- model_type: chat
  engine_config:
    tp: 1
    extra:
      reasoning-parser: qwen-qwq
      tool-call-parser: qwen3
  backends:
  - name: turbomind
    communicators:
    - nccl
  - name: pytorch
    communicators:
    - nccl
  test_coverage:
  - interface
  interface:
  - reasoning_parser
  - tool_parser
  gen_config:
    chat-template-kwargs:
      enable_thinking: true
