# HF model id: Qwen/Qwen3-VL-30B-A3B-Instruct

a100:
- model_type:
  - chat
  - vl
  engine_config:
    tp: 2
  backends:
  - name: pytorch
    communicators:
    - nccl
  test_coverage:
  - func
  - mllm_evaluate
  quantization:
    pytorch:
    - kvint8
- model_type:
  - chat
  - vl
  engine_config:
    tp: 2
    extra:
      logprobs-mode: raw_logprobs
      enable-return-routed-experts: true
  backends:
  - name: pytorch
    communicators:
    - nccl
  test_coverage:
  - interface
  interface:
  - chat_completions_v1
  - generate_logprob
  - generate_experts
- model_type:
  - chat
  - vl
  engine_config:
    tp: 2
    extra:
      logprobs-mode: raw_logprobs
  backends:
  - name: turbomind
    communicators:
    - nccl
  test_coverage:
  - interface
  interface:
  - chat_completions_v1
  - generate_logprob
h:
- model_type:
  - chat
  - vl
  engine_config:
    tp: 2
  backends:
  - name: pytorch
    communicators:
    - nccl
  test_coverage:
  - func
  - mllm_evaluate
  quantization:
    pytorch:
    - kvint8
- model_type:
  - chat
  - vl
  engine_config:
    tp: 2
    extra:
      logprobs-mode: raw_logprobs
      enable-return-routed-experts: true
  backends:
  - name: pytorch
    communicators:
    - nccl
  test_coverage:
  - interface
  interface:
  - chat_completions_v1
  - generate_logprob
  - generate_experts
- model_type:
  - chat
  - vl
  engine_config:
    tp: 2
    extra:
      logprobs-mode: raw_logprobs
  backends:
  - name: turbomind
    communicators:
    - nccl
  test_coverage:
  - interface
  interface:
  - chat_completions_v1
  - generate_logprob
ascend:
- model_type: vl
  engine_config:
    tp: 4
  backends:
  - name: pytorch
    communicators:
    - nccl
  test_coverage:
  - func
  - mllm_evaluate
