name: daily_ete_test

on:
  workflow_dispatch:
    inputs:
      repo_org:
        required: false
        description: 'Tested repository organization name. Default is InternLM'
        type: string
        default: 'InternLM/lmdeploy'
     
env:
  HOST_PIP_CACHE_DIR: /nvme/github-actions/pip-cache
  HOST_LOCALTIME: /usr/share/zoneinfo/Asia/Shanghai
  OUTPUT_FOLDER: cuda11.8_dist_${{ github.run_id }}
  ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true
  REPORT_DIR: /nvme/qa_test_models/test-reports/${{ github.run_id }}
  COV_PATH: /opt/py3/lib/python3.10/site-packages/lmdeploy

jobs:
  test_tools:
    runs-on: [self-hosted, linux-a100-2]
    timeout-minutes: 420
    env:
      PYTHONPATH: /nvme/qa_test_models/offline_pkg/LLaVA
      MODELSCOPE_CACHE: /root/modelscope_hub
      MODELSCOPE_MODULES_CACHE: /root/modelscope_modules
    steps:
      - name: step1
        run: |
          echo ${{ github.run_number }}
          echo ${{ github.run_attempt }}
      - name: step2
        run: |
          echo ${{ github.run_number }}
          echo ${{ github.run_attempt }}
          sleep 300
      - name: step3
        run: |
          echo ${{ github.run_number }}
          echo ${{ github.run_attempt }}
     
