name: daily_ete_test

on:
  workflow_dispatch:
    inputs:
      repo_org:
        required: false
        description: 'Tested repository organization name. Default is InternLM'
        type: string
        default: InternLM
      repo_ref:
        required: false
        description: 'Set branch or tag or commit id. Default is "main"'
        type: string
        default: 'main'
      backend:
        required: true
        description: 'Set backend testcase filter: turbomind or pytorch or turbomind, pytorch. Default is "["turbomind", "pytorch"]"'
        type: string
        default: '["turbomind", "pytorch"]'
      model:
        required: true
        description: 'Set testcase module filter: chat, restful, pipeline, quantization. Default contains all models'
        type: string
        default: '["quantization","convert","pipeline","restful","chat","interface-pipeline"]'
  schedule:
    - cron:  '00 18 * * *'

env:
  HOST_PIP_CACHE_DIR: /nvme/github-actions/pip-cache
  HOST_LOCALTIME: /usr/share/zoneinfo/Asia/Shanghai


jobs:
  test_functions:
    runs-on: [self-hosted, linux-a100]
    timeout-minutes: 240
    env:
      REPORT_DIR: /nvme/qa_test_models/test-reports
    steps:
      - name: Test lmdeploy - quantization w4a16
        continue-on-error: true
        if: (contains(fromJSON(${{github.event.inputs.backend}}), 'turbomind') && contains(fromJSON(${{github.event.inputs.model}}), 'quantization'))
        run: |
          echo contains(fromJSON(${{github.event.inputs.backend}}), 'turbomind')
          echo contains(fromJSON(${{github.event.inputs.model}}), 'turbomind')
      - name: Test lmdeploy - quantization kv int8
        continue-on-error: true
        if: contains(fromJSON(${{github.event.inputs.backend}}), 'turbomind') && contains(fromJSON(${{github.event.inputs.model}}), 'quantization')
        run: |
          echo contains(fromJSON(${{github.event.inputs.backend}}), 'turbomind')
          echo contains(fromJSON(${{github.event.inputs.model}}), 'turbomind')
      - name: Test lmdeploy - quantization w8a8
        continue-on-error: true
        if: contains(fromJSON(${{github.event.inputs.backend}}), 'pytorch') && contains(fromJSON(${{github.event.inputs.model}}), 'quantization')
        run: |
          echo contains(fromJSON(${{github.event.inputs.backend}}), 'turbomind')
          echo contains(fromJSON(${{github.event.inputs.model}}), 'turbomind')
      - name: Test lmdeploy - quantization kv int8 and w4a16
        continue-on-error: true
        if: contains(fromJSON(${{github.event.inputs.backend}}), 'turbomind') && contains(fromJSON(${{github.event.inputs.model}}), 'quantization')
        run: |
          echo contains(fromJSON(${{github.event.inputs.backend}}), 'turbomind')
          echo contains(fromJSON(${{github.event.inputs.model}}), 'turbomind')
      - name: Test lmdeploy - convert
        continue-on-error: true
        if: contains(fromJSON(${{github.event.inputs.backend}}), 'turbomind') && contains(fromJSON(${{github.event.inputs.model}}), 'convert')
        run: |
          echo contains(fromJSON(${{github.event.inputs.backend}}), 'turbomind')
          echo contains(fromJSON(${{github.event.inputs.model}}), 'turbomind')
      - name: Test lmdeploy - chat workspace
        continue-on-error: true
        if: contains(fromJSON(${{github.event.inputs.backend}}), 'turbomind') && contains(fromJSON(${{github.event.inputs.model}}), 'chat')
        timeout-minutes: 20
        run: |
          echo contains(fromJSON(${{github.event.inputs.backend}}), 'turbomind')
          echo contains(fromJSON(${{github.event.inputs.model}}), 'turbomind')
      - name: Test lmdeploy - chat hf turbomind
        continue-on-error: true
        if: contains(fromJSON(${{github.event.inputs.backend}}), 'turbomind') && contains(fromJSON(${{github.event.inputs.model}}), 'chat')
        timeout-minutes: 20
        run: |
          echo contains(fromJSON(${{github.event.inputs.backend}}), 'turbomind')
          echo contains(fromJSON(${{github.event.inputs.model}}), 'turbomind')
      - name: Test lmdeploy - chat hf torch
        continue-on-error: true
        if: contains(fromJSON(${{github.event.inputs.backend}}), 'pytorch') && contains(fromJSON(${{github.event.inputs.model}}), 'chat')
        timeout-minutes: 20
        run: |
          echo contains(fromJSON(${{github.event.inputs.backend}}), 'turbomind')
          echo contains(fromJSON(${{github.event.inputs.model}}), 'turbomind')
      - name: Test lmdeploy - pipeline turbomind
        continue-on-error: true
        if: contains(fromJSON(${{github.event.inputs.backend}}), 'turbomind') && contains(fromJSON(${{github.event.inputs.model}}), 'pipeline')
        timeout-minutes: 25
        run: |
          echo contains(fromJSON(${{github.event.inputs.backend}}), 'turbomind')
          echo contains(fromJSON(${{github.event.inputs.model}}), 'turbomind')
      - name: Test lmdeploy - pipeline torch
        continue-on-error: true
        if: contains(fromJSON(${{github.event.inputs.backend}}), 'pytorch') && contains(fromJSON(${{github.event.inputs.model}}), 'pipeline')
        timeout-minutes: 25
        run: |
          echo contains(fromJSON(${{github.event.inputs.backend}}), 'turbomind')
          echo contains(fromJSON(${{github.event.inputs.model}}), 'turbomind')
      - name: Test lmdeploy - restful turbomind
        continue-on-error: true
        if: contains(fromJSON(${{github.event.inputs.backend}}), 'turbomind') && contains(fromJSON(${{github.event.inputs.model}}), 'restful')
        timeout-minutes: 30
        run: |
          echo contains(fromJSON(${{github.event.inputs.backend}}), 'turbomind')
          echo contains(fromJSON(${{github.event.inputs.model}}), 'turbomind')
      - name: Test lmdeploy - restful torch
        continue-on-error: true
        if: contains(fromJSON(${{github.event.inputs.backend}}), 'pytorch') && contains(fromJSON(${{github.event.inputs.model}}), 'restful')
        timeout-minutes: 40
        run: |
          echo contains(fromJSON(${{github.event.inputs.backend}}), 'turbomind')
          echo contains(fromJSON(${{github.event.inputs.model}}), 'turbomind')
      - name: Test lmdeploy - interface pipeline turbomind case
        continue-on-error: true
        if: contains(fromJSON(${{github.event.inputs.backend}}), 'turbomind') && contains(fromJSON(${{github.event.inputs.model}}), 'interface-pipeline')
        timeout-minutes: 20
        run: |
          echo contains(fromJSON(${{github.event.inputs.backend}}), 'turbomind')
          echo contains(fromJSON(${{github.event.inputs.model}}), 'turbomind')
      - name: Test lmdeploy - rerun all fail cases
        timeout-minutes: 30
        run: |
          echo contains(fromJSON(${{github.event.inputs.backend}}), 'turbomind')
          echo contains(fromJSON(${{github.event.inputs.model}}), 'turbomind')
    


